// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNDNZp9skXPduXQThXw-AlJypd9kg1II8',
    appId: '1:971857908357:android:815da727342a4fd8644fec',
    messagingSenderId: '971857908357',
    projectId: 'flutter-bon-appetit',
    storageBucket: 'flutter-bon-appetit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBIheBpf-pwl6Sj4qUPMbz3vV0RAihquk',
    appId: '1:971857908357:ios:63c74f6b35655a57644fec',
    messagingSenderId: '971857908357',
    projectId: 'flutter-bon-appetit',
    storageBucket: 'flutter-bon-appetit.appspot.com',
    iosClientId:
        '971857908357-jh1c3g70r61pp4t9s0dsfvvas6f7jib9.apps.googleusercontent.com',
    iosBundleId: 'com.franca.bon.appetit.bonAppetit',
  );
}
