class RecipeFilters {
  static const List<String> popular = [
    "Basically",
    "Chicken",
    "Healthyish",
    "Pasta",
    "Salad",
    "Steak",
    "Weeknight Meals",
  ];

  static const List<String> mealsCourse = [
    "Breakfast",
    "Dinner",
    "Drinks",
    "Lunch",
    "Main",
    "Side",
    "Snack",
    "Starter",
  ];

  static const List<String> dietaryConcerns = [
    "Gluten-Free",
    "Healthyish",
    "Vegan",
    "Vegetarian",
  ];

  static const List<String> ingredients = [
    "Apple",
    "Bean",
    "Beef",
    "Broccoli",
    "Brussels Sprout",
    "Cabbage",
    "Cake",
    "Carrot",
    "Cauliflower",
    "Chicken",
    "Chocolate",
    "Citrus",
    "Cookie",
    "Cranberry",
    "Duck",
    "Egg",
    "Eggplant",
    "Fish",
    "Fruit",
    "Green Bean",
    "Ground Beef",
    "Ham",
    "Kale",
    "Lamb",
    "Leafy Greens",
    "Lemon",
    "Mushroom",
    "Pasta",
    "Pork",
    "Potato",
    "Rice",
    "Salmon",
    "Scallop",
    "Seafood",
    "Shellfish",
    "Shrimp",
    "Spinach",
    "Steak",
    "Sweet Potato",
    "Tofu",
    "Tomato",
    "Turkey",
    "Vegan",
    "Zucchini",
  ];
}
